from . import load_exchanges, load_gambling, load_mining, load_historic, load_services, load_exchanges_eth, load_scams_eth

def run():
    print('Saving Exchanges entities...')
    load_exchanges.save_Exchanges()
    print('Saving Exchanges addresses...')
    load_exchanges.save_Addresses()
    print('Saving Gambling entities...')
    load_gambling.save_Gambling()
    print('Saving Gambling addresses...')
    load_gambling.save_Addresses()
    print('Saving Mining entities...')
    load_mining.save_Mining()
    print('Saving Mining addresses...')
    load_mining.save_Addresses()
    print('Saving Historic entities...')
    load_historic.save_Historic()
    print('Saving Historic addresses...')
    load_historic.save_Addresses()
    print('Saving Services entities...')
    load_services.save_Services()
    print('Saving Services addresses...')
    load_services.save_Addresses()
    print('Saving Exchanges entities...')
    load_exchanges_eth.save_Exchanges()
    print('Saving Exchanges addresses...')
    load_exchanges_eth.save_Addresses()
    print('Saving Scams entities...')
    load_scams_eth.save_Scams()