# Generated by Django 4.2.dev20220729062627 on 2022-09-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=100)),
                ('address_tag', models.CharField(max_length=100)),
                ('address_country', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='search',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
