# Generated by Django 4.1 on 2022-09-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.CharField(default='New Dashboard', max_length=50),
        ),
        migrations.AlterField(
            model_name='search',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
