# Generated by Django 4.2.dev20220729062627 on 2022-09-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entities_alter_dashboard_id_alter_search_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entities',
            new_name='Entity',
        ),
    ]
