# Generated by Django 4.1.1 on 2022-10-21 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_entities_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('transactions', models.CharField(max_length=1073741824, null=True)),
                ('first_transaction', models.CharField(max_length=200, null=True)),
                ('informant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='address_name',
            new_name='wallet_name',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='address_tag',
            new_name='wallet_tag',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='address',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='search',
            name='notes',
        ),
        migrations.AddField(
            model_name='entity',
            name='id',
            field=models.BigAutoField(auto_created=True, default=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WebAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_address', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.address', to_field='address')),
                ('informant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SugestedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('informant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entity')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entity'),
        ),
        migrations.AddIndex(
            model_name='webappearance',
            index=models.Index(fields=['address'], name='app_webappe_address_275a95_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address'], name='app_address_address_d03e8f_idx'),
        ),
    ]
