# Generated by Django 4.1.1 on 2022-10-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_sugestedtag_suggestedtag_remove_note_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='wallet_id',
            new_name='entity_id',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='wallet_name',
            new_name='entity_name',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='wallet_tag',
            new_name='entity_tag',
        ),
    ]
