# Generated by Django 4.1.1 on 2022-10-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_wallet_id_address_entity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webappearance',
            name='web_address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
