# Generated by Django 4.1.1 on 2022-10-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_webappearance_web_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='transactions',
            new_name='last_search',
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
