# Generated by Django 4.1.1 on 2022-11-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_transactions_address_last_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='downvotes',
            field=models.CharField(blank=True, max_length=1073741824, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='upvotes',
            field=models.CharField(blank=True, max_length=1073741824, null=True),
        ),
    ]
