# Generated by Django 4.1.1 on 2022-11-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_note_downvotes_note_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='downvotes',
            field=models.CharField(blank=True, default='', max_length=1073741824, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='upvotes',
            field=models.CharField(blank=True, default='', max_length=1073741824, null=True),
        ),
    ]
