# Generated by Django 4.1.1 on 2022-11-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_note_downvotes_alter_note_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webappearance',
            name='web_address',
            field=models.CharField(max_length=100),
        ),
    ]
